#ifndef WORKERS_H
#define WORKERS_H

#include "include.h"

extern mtx_t queue_mutex;
extern cnd_t job_available;
extern const int MAX_JOBS;
extern bool RUNNING;

typedef struct Job{
    ChunkTable* table;
    int cx, cy, cz;
    struct Job* next_job_entry;
}Job;

extern mtx_t result_mutex;
extern cnd_t result_ready;
extern mtx_t chunk_table_mutex;

typedef struct JobResult {
    Chunk* chunk; // The fully block-generated chunk
    ChunkTable* table; // Reference to the world table

    int cx, cy, cz;
    bool is_new_chunk; // FIX: Track if this is a new chunk or regeneration

    // Raw Mesh Data buffers generated by the worker
    float* grass_vertices;
    float* grass_normals;
    float* grass_uvs;
    unsigned char* grass_colors;
    int grass_vert_count;

    float* dirt_vertices;
    float* dirt_normals;
    float* dirt_uvs;
    unsigned char* dirt_colors;
    int dirt_vert_count;

    float* stone_vertices;
    float* stone_normals;
    float* stone_uvs;
    unsigned char* stone_colors;
    int stone_vert_count;

    struct JobResult* next_result_entry;
} JobResult;


void job_push(Job* job);
Job* job_pop();
bool job_queue_empty();

void result_push(JobResult* result);
JobResult* result_pop();
bool result_queue_empty();


int chunk_generator_worker(void* arg);
Job* create_job(ChunkTable* table, int cx, int cy, int cz);

// FIX: New function that handles deduplication
bool request_chunk_job(ChunkTable* table, int cx, int cy, int cz);

// Expose pending job tracking for RegenerateChunk
bool is_job_pending(int cx, int cy, int cz);
void add_pending_job(int cx, int cy, int cz);

#endif